name: FastAPI CI

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: mydatabase
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d mydatabase"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: |
          pytest

      - name:  Validate Docker image tags for AWS ECR
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_BACKEND_REPO: ${{ secrets.ECR_BACKEND_REPO }}
          ECR_FRONTEND_REPO: ${{ secrets.ECR_FRONTEND_REPO }}
        run: |
          echo " Validating Docker image tags..."
          BACKEND_TAG="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_BACKEND_REPO:ci-test"
          FRONTEND_TAG="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_FRONTEND_REPO:ci-test"

          docker build -t $BACKEND_TAG ./backend
          docker build -t $FRONTEND_TAG ./frontend

          echo "Backend image: $BACKEND_TAG"
          echo " Frontend image: $FRONTEND_TAG"

          docker images | grep "$AWS_ACCOUNT_ID" || (echo " Image tag does not include the expected AWS account ID" && exit 1)
